version: '3.8'

services:
  weather-monitor:
    build: .
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      # Persist database file
      - ./database.json:/app/database.json
      # Optional: Mount backups directory for persistence
      - ./backups:/app/backups
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/database"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge 