version: '3'
services:
  weather-monitor:
    image: python:3.11-slim
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      - /Public/weather-monitor/server.py:/app/server.py
      - /Public/weather-monitor/index.html:/app/index.html
      - /Public/weather-monitor/script.js:/app/script.js
      - /Public/weather-monitor/styles.css:/app/styles.css
      - /Public/weather-monitor/requirements.txt:/app/requirements.txt
      - /Public/weather-monitor/database.json:/app/database.json
      - /Public/weather-monitor/Images:/app/Images
      - /Public/weather-monitor/backups:/app/backups
    working_dir: /app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt && python server.py" 