#!/bin/bash

# Weather Alert Monitor - QNAP Public Directory Deployment
# Path: /Public/weather-monitor

echo "🌤️  Weather Alert Monitor - QNAP Public Directory Setup"
echo "======================================================"

echo "📋 Container Station Deployment Steps for /Public/weather-monitor"
echo "==============================================================="
echo ""
echo "Step 1: Prepare Directory Structure"
echo "----------------------------------"
echo "1. Open File Station in QTS"
echo "2. Navigate to /Public/"
echo "3. Create folder: weather-monitor"
echo "4. Inside weather-monitor, create:"
echo "   - data folder"
echo "   - backups folder"
echo "5. Upload all project files to weather-monitor folder"
echo ""
echo "Step 2: Container Station Setup"
echo "------------------------------"
echo "1. Open Container Station in QTS"
echo "2. Go to Create → Application"
echo "3. Choose Docker Compose"
echo "4. Copy and paste this YAML:"
echo ""
echo "services:"
echo "  weather-monitor:"
echo "    image: python:3.11-slim"
echo "    container_name: weather-alert-monitor"
echo "    ports:"
echo "      - \"8000:8000\""
echo "    volumes:"
echo "      - ./:/app"
echo "      - /Public/weather-monitor/data/database.json:/app/database.json"
echo "      - /Public/weather-monitor/backups:/app/backups"
echo "    working_dir: /app"
echo "    environment:"
echo "      - FLASK_ENV=production"
echo "      - PYTHONUNBUFFERED=1"
echo "    restart: unless-stopped"
echo "    command: >"
echo "      sh -c \"pip install -r requirements.txt && python server.py\""
echo ""
echo "Step 3: Verify Volume Mappings"
echo "-----------------------------"
echo "In Container Station → Applications → Your App → Settings → Volumes:"
echo "- ./ → /app (project files)"
echo "- /Public/weather-monitor/data/database.json → /app/database.json"
echo "- /Public/weather-monitor/backups → /app/backups"
echo ""
echo "Step 4: Start and Access"
echo "-----------------------"
echo "1. Click Start in Container Station"
echo "2. Wait for container to start (first run takes a few minutes)"
echo "3. Access at: http://YOUR_QNAP_IP:8000"
echo ""
echo "📁 Required File Structure:"
echo "=========================="
echo "/Public/weather-monitor/"
echo "├── server.py"
echo "├── requirements.txt"
echo "├── index.html"
echo "├── script.js"
echo "├── styles.css"
echo "├── database.json (if you have one)"
echo "├── data/"
echo "│   └── database.json (will be created automatically)"
echo "└── backups/"
echo ""
echo "✅ Success Indicators:"
echo "===================="
echo "- Container status shows 'Running' in Container Station"
echo "- Logs show 'Starting Weather Alert Monitor Server...'"
echo "- You can access http://YOUR_QNAP_IP:8000 in your browser"
echo "- The web interface loads and shows your weather monitor" 