services:
  weather-monitor:
    image: python:3.11-slim
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      - /Public/weather-monitor/data/database.json:/app/database.json
      - /Public/weather-monitor/backups:/app/backups
    working_dir: /app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    command: >
      sh -c "pip install Flask flask_cors && cat > server.py << 'EOF'
from flask import Flask, request, jsonify
from flask_cors import CORS
import json

app = Flask(__name__)
CORS(app)

@app.route('/')
def home():
    return 'Weather Alert Monitor is running on QNAP!'

@app.route('/api/database')
def db_info():
    return json.dumps({'status': 'running', 'message': 'Server is operational'})

if __name__ == '__main__':
    print('Starting Weather Alert Monitor Server...')
    app.run(host='0.0.0.0', port=8000)
EOF
      && python server.py" 