services:
  weather-monitor:
    image: python:3.11-slim
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      # Mount the project files from Public directory
      - /Public/weather-monitor:/app
      # Data persistence
      - /Public/weather-monitor/data/database.json:/app/database.json
      - /Public/weather-monitor/backups:/app/backups
    working_dir: /app
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "ls -la /app && echo 'Files in /app:' && ls -la && echo 'Installing requirements...' && pip install --no-cache-dir -r requirements.txt && echo 'Starting server...' && python server.py" 