version: '3'
services:
  weather-monitor:
    image: python:3.11-slim
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      - /Public/weather-monitor:/app
      - /Public/weather-monitor/data/database.json:/app/database.json
      - /Public/weather-monitor/backups:/app/backups
    working_dir: /app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    command: >
      sh -c "pip install Flask flask_cors && ls -la && python server.py" 