services:
  weather-monitor:
    image: python:3.11-slim
    container_name: weather-alert-monitor
    ports:
      - "8000:8000"
    volumes:
      # Mount the entire project directory
      - ./:/app
      # QNAP-specific data persistence
      - /share/Container/weather-monitor/data/database.json:/app/database.json
      - /share/Container/weather-monitor/backups:/app/backups
    working_dir: /app
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt && python server.py" 